
services:
  db:
    image: mysql:8.4.2
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456  # Contraseña para el usuario root
      MYSQL_DATABASE: dblluvians     # Base de datos a crear
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_general_ci

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d # Para ejecutar scripts SQL al iniciar
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    environment:
      DB_HOST: db
      DB_USER: root                   # Utiliza el usuario root
      DB_PASSWORD: 123456             # Utiliza la misma contraseña configurada para root
      DB_NAME: dblluvians
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
