### Obtener todos los usuarios
GET http://localhost:3000/api/users

### Obtener un usuario por ID
GET http://localhost:3000/api/users/2

### Crear un nuevo usuario
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "password": "1234567",
  "dni": 10335678,
  "emergency_number": "1476547721",
  "phone": "313477789",
  "birthDate": "1991-01-01",
  "gender": "Male",
  "roleId": 2,
  "locationId": 1,
  "enabled": true
}

### Actualizar un usuario por ID
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "phone": "987654321",
  "enabled": true

}

### Soft Delete (marcar como deshabilitado)
DELETE http://localhost:3000/api/users/1
